// constants/dummy.ts
export const dummyCards = [
  {
    id: '1',
    title: 'ChatGPT Code Interpreter 🔍',
    summary: 'Runs Python in-browser for data analysis and plotting.',
    why: 'Makes data skills accessible to all.',
    upskill: 'Learn Python, Pandas, and Matplotlib basics.',
    sourceUrl: 'https://openai.com',
  },
  {
    id: '2',
    title: 'AI-Powered Resume Builder Launched 📄',
    summary: 'Craft tailored resumes in seconds with GPT-4-powered suggestions.',
    why: 'Helps job seekers stand out in tech fields.',
    upskill: 'Explore tools like Rezi, TealHQ, or Resume.io.',
    sourceUrl: 'https://resumetools.ai',
  },
  {
    id: '3',
    title: 'Manus AI Assists Coders ⚙️',
    summary: 'AI agent helps developers automate tasks using natural prompts.',
    why: 'Improves productivity and reduces manual effort.',
    upskill: 'Learn prompt engineering and IDE integrations.',
    sourceUrl: 'https://manus.ai',
  },
  {
    id: '4',
    title: 'Google Gemini Integrates in Android 📱',
    summary: 'Gemini replaces Google Assistant with multimodal intelligence.',
    why: 'Changes how users interact with their phones.',
    upskill: 'Experiment with Gemini apps and workflows.',
    sourceUrl: 'https://blog.google/technology/ai/',
  },
  {
    id: '5',
    title: 'OpenAI GPT-5 Beta Testing Begins 🚀',
    summary: 'Next-gen LLM features better reasoning and longer memory.',
    why: 'Could redefine AI productivity and search experiences.',
    upskill: 'Stay updated on API docs and research papers.',
    sourceUrl: 'https://openai.com',
  },
  {
    id: '6',
    title: 'Notion Adds Q&A AI Assistant 💬',
    summary: 'Ask your workspace questions and get smart answers instantly.',
    why: 'Boosts personal and team productivity.',
    upskill: 'Master knowledge management tools like Notion.',
    sourceUrl: 'https://www.notion.so/product/ai',
  },
  {
    id: '7',
    title: 'Build Your Own Chatbot with LangChain 🤖',
    summary: 'LangChain offers modular LLM components to build apps.',
    why: 'Empowers developers to create custom AI workflows.',
    upskill: 'Learn Python, LangChain, and vector databases.',
    sourceUrl: 'https://www.langchain.com',
  },
  {
    id: '8',
    title: 'AI Translates Videos in Your Voice 🌐',
    summary: 'Tools like HeyGen offer voice-preserving dubbing.',
    why: 'Break language barriers with personalized content.',
    upskill: 'Try HeyGen, Dubverse, and ElevenLabs APIs.',
    sourceUrl: 'https://www.heygen.com',
  },
  {
    id: '9',
    title: 'Firefly AI Generates Stunning Images 🎨',
    summary: 'Adobe’s generative AI creates designs inside Photoshop.',
    why: 'Democratizes design with easy text-to-image tools.',
    upskill: 'Practice with Firefly prompts and layers.',
    sourceUrl: 'https://firefly.adobe.com',
  },
  {
    id: '10',
    title: 'AI in Finance: Jarvis Launched 💰',
    summary: 'Jarvis helps users manage budgets and plan investments.',
    why: 'AI makes personal finance smarter.',
    upskill: 'Learn FinTech basics and budgeting habits.',
    sourceUrl: 'https://jarvis.money',
  },
];
