// constants/dummy.ts
export const dummyCards = [
  {
    id: '1',
    title: 'ChatGPT Code Interpreter 🔍',
    summary: 'ChatGPT’s Code Interpreter lets users write and run Python code inside the browser for tasks like visualizations, data analysis, and spreadsheet automation. No local setup needed.',
    why: 'It democratizes access to data skills by enabling even non-programmers to analyze data, generate plots, and automate reports using just natural language prompts.',
    upskill: 'Learn core Python, practice with Pandas for tabular data, and use Matplotlib or Seaborn for beautiful charts. Try OpenAI’s built-in advanced tools for practice.',
    sourceUrl: 'https://openai.com',
    image: 'https://res.cloudinary.com/dcpa501nb/image/upload/v1753146530/ChatGPT-1_zigvdc.jpg',
  },
  {
    id: '2',
    title: 'Manus AI Assists Coders ',
    summary: 'Manus AI helps developers speed up repetitive coding tasks, generate components, and integrate APIs using natural-language prompts',
    why: 'It minimizes mental overload by automating common tasks and lets developers stay focused on higher-level problem-solving.',
    upskill: 'Explore prompt engineering, customize Manus workflows, and learn IDE extensions to connect Manus with GitHub. ',
    sourceUrl: 'https://manus.ai',
    image: 'https://res.cloudinary.com/dcpa501nb/image/upload/v1753146599/70404d72-e2d3-4d06-a949-5cbb175905b2_5ca7620c_xutegt.jpg',
  },
  {
    id: '3',
    title: 'AI-Powered Resume Builder 📄',
    summary: 'With GPT-4-powered resume builders, users can instantly generate resumes tailored to specific roles, using keywords, formats, and tone that boost selection chances.',
    why: 'In a competitive job market, standing out matters. AI can help by formatting resumes, optimizing job titles, and adapting them to different industries and platforms.',
    upskill: 'Learn resume optimization, test tools like Rezi, TealHQ, Resume.io, and analyze how AI aligns skills with job descriptions to improve your interview call rates.',
    sourceUrl: 'https://resumetools.ai',
    image: 'https://www.rezi.ai/_next/image?url=%2Fassets%2Fresume-image.png&w=1920&q=75',
  },
  {
    id: '4',
    title: 'Google Gemini Comes to Android 📱',
    summary: 'Gemini replaces Google Assistant on Android with advanced multimodal capabilities — understanding text, images, and voice commands with deeper contextual awareness.',
    why: 'Gemini is Google’s next-gen AI agent that makes your phone feel smarter. It reads screen context, suggests actions, and blends tasks seamlessly with voice and visuals.',
    upskill: 'Experiment with Gemini in Pixel Labs, test automation flows, and learn how apps can use Gemini APIs for more responsive, helpful mobile experiences.',
    sourceUrl: 'https://blog.google/technology/ai/',
    image: 'https://cdn.vox-cdn.com/thumbor/nDFduFB6CB1VX-P7Y4ePlX4aUU4=/0x0:2040x1360/1400x933/filters:focal(1020x680:1021x681)/cdn.vox-cdn.com/uploads/chorus_asset/file/24530655/STK093_Google_01.jpg',
  },
  {
    id: '5',
    title: 'Notion Adds Q&A AI Assistant 💬',
    summary: 'Notion’s new AI assistant can answer questions from your notes, summarize documents, generate content, and even suggest project plans inside your workspace.',
    why: 'It streamlines productivity by reducing the time spent digging through pages. Now you can just ask and get concise, intelligent responses for your workspace tasks.',
    upskill: 'Master using Notion databases, create structured notes, and explore how Notion AI interacts with task trackers, calendars, and internal documentation.',
    sourceUrl: 'https://www.notion.so/product/ai',
    image: 'https://res.cloudinary.com/dcpa501nb/image/upload/v1753147567/Notion-AI_f6ugjs.jpg',
  },
  {
    id: '6',
    title: 'Build Chatbots with LangChain 🤖',
    summary: 'LangChain allows developers to combine large language models, memory, APIs, and databases to build interactive, smart, and context-aware conversational apps.',
    why: 'LangChain provides tools to make AI chatbots more modular, track memory, and build customized logic flows, moving beyond basic Q&A into real utility apps.',
    upskill: 'Understand chain components, work with vector stores, use OpenAI + Pinecone, and build end-to-end flows that respond dynamically to user input.',
    sourceUrl: 'https://www.langchain.com',
    image: 'https://miro.medium.com/v2/resize:fit:1400/format:webp/1*E_G6Mn5Cy8SKWSE4A1cXWA.png',
  },
  {
    id: '7',
    title: 'Firefly AI Designs with Prompts 🎨',
    summary: 'Adobe Firefly enables users to generate stunning illustrations, logos, and mockups simply by typing prompts in natural language and tweaking styles.',
    why: 'This lowers the barrier for non-designers and freelancers to create compelling graphics and branded content faster than ever — without learning Photoshop.',
    upskill: 'Practice Firefly prompt styles, use Adobe layers smartly, and learn to blend images with your brand guidelines. Create content calendars visually.',
    sourceUrl: 'https://firefly.adobe.com',
    image: 'https://helpx.adobe.com/content/dam/help/en/firefly/using/firefly-homepage/_jcr_content/main-pars/image/image.img.jpg',
  },
  {
    id: '8',
    title: 'AI Translates Videos in Your Voice 🌐',
    summary: 'Tools like HeyGen and Dubverse allow users to auto-dub videos in their original voice and language, using AI to retain tone and emotion across languages.',
    why: 'Perfect for content creators and educators — AI voice translation boosts accessibility and lets you localize videos with ease, speed, and personal voice.',
    upskill: 'Explore HeyGen, ElevenLabs, Dubverse, and try uploading your short videos for multilingual dubbing. Learn voice synthesis models and timelines.',
    sourceUrl: 'https://www.heygen.com',
    image: 'https://images.ctfassets.net/lzny33ho1g45/4lwXIkLb9FtUdOJfDjc57h/114cdfc5e2a6bc5ef12c2f3e3ed6b7b4/heygen-lead-image.jpeg',
  },
  {
    id: '9',
    title: 'OpenAI GPT-5 Beta Starts 🚀',
    summary: 'The GPT-5 beta introduces better reasoning, longer memory, real-time context understanding, and improved multimodal capabilities for enterprise apps.',
    why: 'As OpenAI pushes GPT-5 into production, it will change the way businesses use AI in tools, customer support, and data analytics — setting new standards.',
    upskill: 'Join the beta program, explore GPT-5 APIs, and follow OpenAI’s developer blog to learn real use cases in customer support, writing, and education.',
    sourceUrl: 'https://openai.com',
    image: 'https://res.cloudinary.com/dcpa501nb/image/upload/v1753147841/GPT-5_dan68y.jpg',
  },
  {
    id: '10',
    title: 'AI in Finance: Meet Jarvis 💰',
    summary: 'Jarvis uses AI to create smart personal finance plans, auto-categorize expenses, suggest investments, and alert users about unusual spending patterns.',
    why: 'For young professionals, AI tools like Jarvis make money management smarter, help reduce debt, and provide personalized strategies based on goals.',
    upskill: 'Understand how fintech works, explore budgeting apps, test savings plans, and set goals using AI tools integrated with your bank and habits.',
    sourceUrl: 'https://jarvis.money',
    image: 'https://cdn.analyticsvidhya.com/wp-content/uploads/2023/07/Fintech.jpg',
  },
];
