export const RSS_FEEDS = {
    // Original Tech Feeds
    techcrunch: "https://techcrunch.com/feed/",
    verge: "https://www.theverge.com/rss/index.xml",
    wired: "https://www.wired.com/feed/rss",
    arstechnica: "https://feeds.arstechnica.com/arstechnica/index",
    engadget: "https://www.engadget.com/rss.xml",
    zdnet: "https://www.zdnet.com/news/rss.xml",
    mashable: "https://mashable.com/feeds/rss/all",
    techradar: "https://www.techradar.com/rss",
    cnet: "https://www.cnet.com/rss/news/",
    venturebeat: "https://venturebeat.com/feed/",
    recode: "https://www.vox.com/rss/technology/index.xml",
    
    // AI & ML Focused Feeds
    geekwire: "https://www.geekwire.com/feed/",
    machine_learning_mastery: "https://machinelearningmastery.com/blog/feed/",
    mark_tech_post: "https://www.marktechpost.com/feed/",
    bairrblog: "https://bair.berkeley.edu/blog/feed.xml",
    googleresearchblog: "https://research.google/blog/rss/",
    mitnewsai: "https://news.mit.edu/rss/topic/artificial-intelligence2",
    ai2people: "https://ai2people.com/feed/",
    techspective: "https://techspective.net/category/technology/artificial-intelligence/feed/",
    qudata: "https://qudata.com/en/news/rss.xml",
    aitrends: "https://www.aitrends.com/feed/",
    metadevlopaiblog: "https://metadevo.com/feed/",
    dailyai: "https://dailyai.com/feed",
    aiworldjournal: "https://aiworldjournal.com/feed",
    aihub: "https://aihub.org/feed?cat=-473",
    marktechpost: "https://marktechpost.com/feed",
    thegradient: "https://thegradient.pub/feed/",
    ainyheter: "https://nyheter.aitool.se/feed",
    aiweeklynews: "http://aiweekly.co/issues.rss",
    cogitotech: "https://www.cogitotech.com/feed/",
    robotwritersai: "https://robotwritersai.com/feed",
    aitimejournal: "https://aitimejournal.com/feed",
    
    // Company AI Blogs
    openaiblog: "https://openai.com/blog/rss/",
    googleaiblog: "https://ai.googleblog.com/feeds/posts/default",
    microsoftaiblog: "https://blogs.microsoft.com/ai/feed/",
    nvidiaaiblog: "https://blogs.nvidia.com/blog/category/ai/feed/",
    metaaiblog: "https://ai.meta.com/blog/rss/",
};