export const aiTools = [
  { name: 'ChatGPT', icon: 'chatbubble-ellipses-outline', url: 'https://chat.openai.com/' },
  { name: 'Gemini', icon: 'planet-outline', url: 'https://gemini.google.com/' },
  { name: 'Claude', icon: 'flash-outline', url: 'https://claude.ai/' },
  { name: 'Midjourney', icon: 'color-palette-outline', url: 'https://www.midjourney.com/' },
  { name: 'Bard', icon: 'bulb-outline', url: 'https://bard.google.com/' },
  { name: 'DALL·E', icon: 'images-outline', url: 'https://openai.com/dall-e' },
  { name: 'Notion AI', icon: 'document-text-outline', url: 'https://www.notion.so/product/ai' },
  { name: 'Fireflies', icon: 'mic-outline', url: 'https://fireflies.ai/' },
  { name: 'Synthesia', icon: 'videocam-outline', url: 'https://www.synthesia.io/' },
  { name: 'Runway ML', icon: 'film-outline', url: 'https://runwayml.com/' },
  { name: 'Replit AI', icon: 'code-slash-outline', url: 'https://replit.com/' },
  { name: 'Copy.ai', icon: 'create-outline', url: 'https://www.copy.ai/' },
  { name: 'Jasper', icon: 'rocket-outline', url: 'https://www.jasper.ai/' },
  { name: 'QuillBot', icon: 'construct-outline', url: 'https://quillbot.com/' },
  { name: 'Grammarly', icon: 'checkmark-done-outline', url: 'https://www.grammarly.com/' },
  { name: 'DeepL', icon: 'language-outline', url: 'https://www.deepl.com/translator' },
  { name: 'Descript', icon: 'musical-notes-outline', url: 'https://www.descript.com/' },
  { name: 'Heygen', icon: 'person-circle-outline', url: 'https://www.heygen.com/' },
  { name: 'Tome', icon: 'book-outline', url: 'https://tome.app/' },
  { name: 'Pictory', icon: 'camera-outline', url: 'https://pictory.ai/' },
]; 